2020-04-08 18:12:14,256 ERROR: Exception on /reset_pasword_request [POST] [in /home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nurbek/Desktop/microblog/app/routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "/home/nurbek/Desktop/microblog/app/email.py", line 19, in send_password_reset_email
    user=user, token=token),
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/nurbek/Desktop/microblog/app/templates/email/reset_password.txt", line 7, in template
    {{ url_for('reset_password' token=token, _external=True) }}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'token'
2020-04-08 18:13:49,599 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 50]
2020-04-08 18:13:59,928 ERROR: Exception on /reset_pasword_request [POST] [in /home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nurbek/Desktop/microblog/app/routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "/home/nurbek/Desktop/microblog/app/email.py", line 19, in send_password_reset_email
    user=user, token=token),
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/nurbek/Desktop/microblog/app/templates/email/reset_password.txt", line 7, in template
    {{ url_for('reset_password' token=token, _external=True) }}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'token'
2020-04-08 18:15:08,170 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 50]
2020-04-08 19:48:09,491 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 50]
2020-04-08 19:49:03,008 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 50]
2020-04-08 20:57:00,908 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-08 21:00:14,376 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-08 21:01:34,620 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-08 21:03:15,591 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-08 21:05:16,094 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-09 18:23:40,708 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-09 19:10:25,942 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 51]
2020-04-09 19:13:00,445 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 52]
2020-04-09 19:17:38,610 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 52]
2020-04-09 19:28:44,394 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 54]
2020-04-09 20:11:07,681 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 54]
2020-04-09 20:12:12,786 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 54]
2020-04-09 20:12:51,506 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 54]
2020-04-09 20:19:08,321 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 54]
2020-04-09 20:20:25,488 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 54]
2020-04-09 20:52:42,501 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 58]
2020-04-09 20:58:52,526 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 58]
2020-04-10 19:31:50,564 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 58]
2020-04-10 20:22:49,761 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 58]
2020-04-13 20:06:41,171 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 75]
2020-04-13 20:06:45,159 ERROR: Exception on / [GET] [in /home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/nurbek/Desktop/microblog/app/main/routes.py", line 52, in before_request
    g.locale = str(get_locale())
  File "/home/nurbek/Desktop/microblog/env/lib/python3.7/site-packages/flask_babel/__init__.py", line 251, in get_locale
    rv = babel.locale_selector_func()
  File "/home/nurbek/Desktop/microblog/app/__init__.py", line 82, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2020-04-13 20:09:22,767 INFO: Microblog [in /home/nurbek/Desktop/microblog/app/__init__.py: 75]
